# Site settings
title: Read
subtitle: Book Shop Guide
email: bookshopguide@gmail.com
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bookshopguide.github.io" # the base hostname & protocol for your site
author:
street_address: 24 Iguana Road
city: Lincoln County
state: Nevada
zip_code: 89044
country: United States of America
phone: (716) 555-5555

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown
