# Site settings
title: Read
subtitle: Book Shop Guide
email: bookshopguide@gmail.com
description: Book shop guide is run by a group of passionate book enthusiasts that want to help others find amazing books to read.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bookshopguide.com" # the base hostname & protocol for your site
author: Book Shop Guide
street_address: 24 Iguana Road
city: Lincoln County
state: Nevada
zip_code: 89044
country: United States of America
phone: (716) 555-5555

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown

paginate: 6

gems:
- jekyll-seo-tag
- jekyll-paginate
